// 授权码管理 - 数据存储层
// 支持文件存储（本地/Electron）和 Redis（生产）

import * as fs from 'fs';
import * as path from 'path';

export interface LicenseCode {
  code: string;
  createdAt: number;
  unlimited: boolean;
  disabled: boolean;
  note?: string;
}

const MAX_DEVICES_PER_LICENSE = 3;

// 文件存储路径
const dataDir = path.join(process.cwd(), 'data');
const licensesFile = path.join(dataDir, 'licenses.json');

// 确保数据目录存在
function ensureDataDir() {
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }
}

// 读取所有授权码
export function getAllLicenses(): LicenseCode[] {
  try {
    ensureDataDir();
    if (!fs.existsSync(licensesFile)) {
      // 初始化默认授权码
      const defaultLicenses: LicenseCode[] = [
        { code: 'LIHUO88888888', createdAt: Date.now(), unlimited: false, disabled: false, note: '管理员授权码' },
        { code: 'TESTER88888888', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码（无限设备）' },
        // 普通授权码（500个）
        { code: 'LIHUO479624', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO244331', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO696506', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO954400', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO844214', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO161940', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO867584', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO570159', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO123643', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO973917', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO256046', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO565594', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO623454', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO145526', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO825670', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO150600', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO338913', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO950938', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO971068', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO685626', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO217878', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO517454', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO253692', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO347121', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO593041', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO893547', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO111292', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO804843', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO117252', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO267357', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO596279', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO620335', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO255233', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO277832', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO213319', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO252354', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO811187', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO360372', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO395706', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO914983', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO949384', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO180882', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO868999', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO735303', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO205875', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO616215', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO343596', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO668534', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO472108', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO836807', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO479101', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO152969', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO617311', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO868475', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO761828', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO408538', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO480447', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO151892', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO221865', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO316751', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO451222', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO810699', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO972335', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO422187', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO189526', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO738405', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO513672', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO495865', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO831935', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO150858', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO684716', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO145391', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO585046', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO662659', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO208711', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO611964', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO216573', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO644338', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO449252', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO125746', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO751021', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO722407', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO177565', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO707167', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO922551', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO316131', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO924495', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO227290', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO811298', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO968506', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO239681', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO596074', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO768623', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO609932', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO919857', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO597423', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO714438', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO141205', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO834025', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO647515', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO855311', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO766180', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO139692', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO917659', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO279901', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO210355', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO435468', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO179093', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO989167', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO642737', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO980044', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO527255', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO703525', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO360278', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO746317', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO917657', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO991485', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO433200', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO340154', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO138476', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO622308', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO482351', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO791513', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO567100', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO414469', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO339187', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO268209', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO418568', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO968301', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO332621', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO548278', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO308428', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO349570', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO848222', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO165092', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO591997', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO244556', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO451100', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO532317', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO711402', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO155973', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO827571', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO508710', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO781696', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO455430', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO977606', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO500525', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO463816', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO233422', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO574025', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO486299', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO182023', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO294875', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO770754', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO819012', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO378405', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO323815', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO520880', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO602651', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO818280', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO245577', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO108924', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO610716', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO288149', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO518976', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO162760', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO904657', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO137743', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO325399', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO930271', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO253151', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO905525', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO934990', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO629232', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO787299', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO320914', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO136100', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO332836', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO721054', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO838799', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO268208', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO792023', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO176546', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO807998', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO397840', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO451856', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO519156', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO844388', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO823483', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO256280', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO325423', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO787402', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO620264', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO513912', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO941626', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO556748', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO353020', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO417184', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO968305', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO635064', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO902953', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO291878', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO717410', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO755870', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO290404', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO962503', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO413300', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO639689', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO664932', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO711010', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO464032', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO543392', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO202286', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO387962', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO717477', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO754971', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO878593', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO945884', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO843800', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO767072', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO751774', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO835836', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO323317', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO756961', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO632366', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO607554', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO629754', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO544449', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO496216', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO112030', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO698948', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO516067', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO985857', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO399623', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO104496', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO829812', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO381508', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO482538', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO842478', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO609766', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO470233', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO367337', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO670072', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO406002', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO258411', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO400196', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO202784', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO965696', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO618124', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO588354', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO687315', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO947963', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO923282', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO692847', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO989110', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO784531', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO675722', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO152157', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO768284', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO124232', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO848875', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO760218', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO223540', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO303539', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO363733', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO174973', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO169565', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO501106', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO722051', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO395032', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO673278', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO296538', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO873873', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO212778', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO812993', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO807808', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO943535', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO317366', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO785225', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO651968', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO412862', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO186459', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO438156', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO621698', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO573728', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO634059', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO577402', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO736358', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO253247', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO363594', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO978051', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO626160', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO802443', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO712428', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO311453', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO567655', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO576405', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO669092', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO408380', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO785507', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO581930', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO673465', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO657348', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO643927', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO236439', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO872391', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO342745', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO261857', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO495719', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO319142', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO319813', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO411408', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO174819', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO629591', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO687251', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO874091', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO297791', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO112839', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO569592', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO313530', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO297084', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO421504', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO385733', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO571824', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO745890', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO127626', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO805515', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO942178', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO680759', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO219241', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO415933', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO270030', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO480139', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO596388', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO559301', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO456589', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO320353', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO637168', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO315118', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO732698', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO896326', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO600223', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO171229', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO257484', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO551290', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO608620', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO873041', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO493647', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO522908', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO396235', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO585038', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO234546', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO212228', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO895906', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO188409', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO172241', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO650826', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO286249', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO453526', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO648872', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO235081', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO473423', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO748580', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO145115', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO348572', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO438789', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO635120', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO196429', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO146835', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO548233', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO479040', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO378586', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO101850', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO891705', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO761547', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO224889', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO358087', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO389346', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO781890', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO375259', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO541251', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO170711', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO545260', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO242497', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO281118', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO854446', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO744687', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO643057', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO372814', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO427677', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO890865', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO247360', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO948174', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO156620', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO932452', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO132351', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO747876', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO294993', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO110530', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO768483', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO971600', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO857927', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO852824', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO692087', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO184229', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO118486', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO502876', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO846048', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO133291', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO906597', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO592533', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO944976', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO759372', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO659174', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO805675', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO154943', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO130492', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO438053', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO339764', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO366800', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO867255', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO647042', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO502593', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO504326', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO449740', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO316139', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO554276', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO601717', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO365922', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO531514', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO720382', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO822791', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO944650', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO274496', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO837139', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO241496', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO257198', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO261247', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO954326', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO927251', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO525374', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO161641', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO218754', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO270479', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO705886', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO998317', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO415702', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO746970', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO262811', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO531087', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO797163', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO777769', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO202592', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO192578', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO841990', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO336605', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO215292', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO479237', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO996327', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO470635', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO382590', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO515672', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO798538', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO825325', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO913033', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO506506', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO188156', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO722093', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO113862', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO782825', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO286223', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO295329', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO347738', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO117693', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO381437', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO951656', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO421806', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO443068', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO404037', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO675293', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO584283', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO930358', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO882100', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO606679', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO810289', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO245137', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO672173', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO628481', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO299007', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO473930', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO904317', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO450690', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO332018', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO118722', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO809767', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO132663', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO306210', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO698296', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO558528', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        { code: 'LIHUO859849', createdAt: Date.now(), unlimited: false, disabled: false, note: '' },
        // 无限设备授权码（10个）
        { code: 'LIHUO327964', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO645224', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO212718', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO310867', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO822701', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO399862', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO592917', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO803469', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO291113', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
        { code: 'LIHUO705045', createdAt: Date.now(), unlimited: true, disabled: false, note: '测试员授权码' },
      ];
      fs.writeFileSync(licensesFile, JSON.stringify(defaultLicenses, null, 2));
      return defaultLicenses;
    }
    const data = fs.readFileSync(licensesFile, 'utf-8');
    return JSON.parse(data);
  } catch {
    return [];
  }
}

// 保存所有授权码
export function saveLicenses(licenses: LicenseCode[]): void {
  ensureDataDir();
  fs.writeFileSync(licensesFile, JSON.stringify(licenses, null, 2));
}

// 生成新授权码
export function generateLicenseCode(unlimited: boolean = false, note?: string): LicenseCode {
  // 生成 LIHUO + 6位随机数字
  const random = Math.floor(100000 + Math.random() * 900000);
  const code = `LIHUO${random}`;
  
  const license: LicenseCode = {
    code,
    createdAt: Date.now(),
    unlimited,
    disabled: false,
    note,
  };

  const licenses = getAllLicenses();
  licenses.push(license);
  saveLicenses(licenses);

  return license;
}

// 禁用/启用授权码
export function toggleLicenseDisabled(code: string): boolean {
  const licenses = getAllLicenses();
  const license = licenses.find(l => l.code === code);
  if (license) {
    license.disabled = !license.disabled;
    saveLicenses(licenses);
    return license.disabled;
  }
  return false;
}

// 删除授权码
export function deleteLicense(code: string): boolean {
  let licenses = getAllLicenses();
  const initialLength = licenses.length;
  licenses = licenses.filter(l => l.code !== code);
  if (licenses.length !== initialLength) {
    saveLicenses(licenses);
    return true;
  }
  return false;
}

// 检查授权码是否有效
export function isLicenseValid(code: string): boolean {
  const licenses = getAllLicenses();
  const license = licenses.find(l => l.code === code);
  return !!(license && !license.disabled);
}

// 检查授权码是否无限设备
export function isLicenseUnlimited(code: string): boolean {
  const licenses = getAllLicenses();
  const license = licenses.find(l => l.code === code);
  return license?.unlimited || false;
}

export { MAX_DEVICES_PER_LICENSE };
